version: "3"

services:
  db:
    image: postgres
    container_name: edugame_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: edugame
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
  api:
    build: .
    ports:
      - "3000"

volumes:
  database-data:
