version: "3"

services:
  db:
    image: postgres
    container_name: edugame_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - back
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - database-data:/var/lib/postgresql/data/
  api:
    build:
      context: .
    ports:
      - "3000"
    networks:
      - back
volumes:
  database-data:

networks:
  back:
